# Generated by Django 4.2.15 on 2025-04-18 07:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geohosting', '0041_delete_webhookevent'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT')])),
                ('data', models.JSONField(blank=True, null=True)),
                ('request_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data', models.JSONField()),
                ('note', models.TextField(blank=True, null=True)),
                ('app_name', models.CharField(blank=True, max_length=256, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geohosting.activity')),
            ],
            options={
                'ordering': ('-triggered_at',),
            },
        ),
        migrations.CreateModel(
            name='LogTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('error', 'Error'), ('success', 'Success')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
