# Generated by Django 4.2.15 on 2025-04-23 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting_event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('to', models.JSONField()),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
    ]
