# Generated by Django 4.2.15 on 2025-04-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_preferences_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='grace_period_days',
            field=models.IntegerField(default=14, help_text='Number of days after expiration that the instance remains active before deletion.'),
        ),
        migrations.AddField(
            model_name='preferences',
            name='reminder_days_after_expiry',
            field=models.IntegerField(default=1, help_text='The number of days after expiration to send the reminder email.'),
        ),
    ]
