# Generated by Django 4.2.15 on 2025-06-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_preferences_grace_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='erpnext_project_code',
            field=models.CharField(blank=True, help_text='The project code of geohosting on ERP.', max_length=100, null=True),
        ),
    ]
