# Generated by Django 4.2.15 on 2024-08-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0011_ticket_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_status',
            field=models.CharField(choices=[('Waiting Payment', 'Waiting Payment'), ('Waiting Configuration', 'Waiting Configuration'), ('Waiting Deployment', 'Waiting Deployment'), ('Deployed', 'Deployed')], default='Waiting Payment', help_text='The status of order.', max_length=256),
        ),
    ]
