# Generated by Django 4.2.15 on 2024-09-12 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0012_salesorder_app_name_alter_salesorder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.salesorder'),
        ),
    ]
