# Generated by Django 4.2.15 on 2024-11-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0028_instance_company_salesorder_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderErpCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('Stripe', 'Stripe'), ('Paystack', 'Paystack')], default='Stripe', help_text='The status of order.', max_length=256, unique=True)),
                ('erp_company', models.CharField(help_text='The erp company that will be used to push to ERP.', max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Sales order erp companies',
            },
        ),
    ]
