# Generated by Django 4.2.15 on 2025-03-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0034_logtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('Deploying', 'Deploying'), ('Starting Up', 'Starting Up'), ('Online', 'Online'), ('Offline', 'Offline'), ('Terminating', 'Terminating'), ('Terminated', 'Terminated')], default='Deploying'),
        ),
    ]
