# Generated by Django 4.2.15 on 2025-04-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0038_instance_expiry_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogTracker',
        ),
    ]
