# Generated by Django 4.2.15 on 2025-04-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0039_delete_logtracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErpRequestLog',
        ),
    ]
