# Generated by Django 4.2.15 on 2025-04-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0040_delete_erprequestlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
    ]
