# Generated by Django 4.2.15 on 2025-04-18 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geohosting', '0041_delete_webhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(help_text='Subscription id on the payment gateway.')),
                ('payment_method', models.CharField(choices=[('Stripe', 'Stripe'), ('Paystack', 'Paystack')], default='Stripe', help_text='The status of order.', max_length=256)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription of the instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.subscription'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription of the instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.subscription'),
        ),
    ]
