# Generated by Django 4.2.15 on 2025-04-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0042_subscription_instance_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='expiry_at',
        ),
    ]
