# Generated by Django 4.2.15 on 2025-04-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    sql = """        
        -- Update vault url to product --
        UPDATE geohosting_product AS pr
        SET vault_url = pg.vault_url
        FROM geohosting_package AS p
        JOIN geohosting_packagegroup AS pg ON p.package_group_id = pg.id
        WHERE pr.id = p.product_id;
    """

    dependencies = [
        ('geohosting', '0043_remove_instance_expiry_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name': 'Jenkins activity type'},
        ),
        migrations.AlterModelOptions(
            name='erpcompany',
            options={'ordering': ('name',), 'verbose_name_plural': 'Erp companies'},
        ),
        migrations.AlterModelOptions(
            name='salesorder',
            options={'verbose_name': 'Sales order', 'verbose_name_plural': 'Sales orders'},
        ),
        migrations.AddField(
            model_name='product',
            name='vault_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.RunSQL(sql, migrations.RunSQL.noop),
    ]
