# Generated by Django 4.2.15 on 2025-04-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0044_alter_activitytype_options_alter_erpcompany_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagegroup',
            name='vault_url',
        ),
    ]
