# Generated by Django 4.2.15 on 2025-04-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0045_remove_packagegroup_vault_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='customer_payment_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
