# Generated by Django 4.2.15 on 2025-05-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0046_subscription_customer_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Payment id on the payment gateway, it needs for paystack.', null=True),
        ),
    ]
