# Generated by Django 4.2.15 on 2025-05-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0047_subscription_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
