# Generated by Django 4.2.15 on 2025-05-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0048_package_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vault_url',
        ),
        migrations.AddField(
            model_name='cluster',
            name='vault_url',
            field=models.URLField(blank=True, help_text='URL of the vault url for getting credential', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='add_on',
            field=models.ManyToManyField(blank=True, null=True, to='geohosting.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_add_on',
            field=models.BooleanField(default=False, help_text='This product cannot be standalone and is not saleable.'),
        ),
        migrations.AddField(
            model_name='product',
            name='password_key_on_vault',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url_as_addon',
            field=models.CharField(blank=True, help_text='URL of the product as add-on, example: geoserver on the geonode is "/geoserver".', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='username_credential',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vault_path',
            field=models.CharField(blank=True, help_text='The path of the vault from the vault_url of the cluster.', max_length=256, null=True),
        ),
    ]
