# Generated by Django 4.2.15 on 2025-06-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0050_ticket_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agreementdetail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='agreementdetail',
            name='erp_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.erpcompany'),
        ),
        migrations.AlterUniqueTogether(
            name='agreementdetail',
            unique_together={('agreement', 'erp_company', 'version')},
        ),
    ]
