# Generated by Django 4.2.15 on 2025-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0051_alter_agreementdetail_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagegroup',
            name='conf_github_path',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='packagegroup',
            name='specification',
            field=models.JSONField(blank=True, help_text='Specification of the package.', null=True),
        ),
    ]
