# Generated by Django 4.2.15 on 2025-07-11 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0052_packagegroup_conf_github_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erpnext_code', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
