# Generated by Django 4.2.15 on 2025-07-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0053_salesorderinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpPaymentTermTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erpnext_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='erpcompany',
            name='invoice_from_sales_invoice',
            field=models.BooleanField(default=False, help_text='If checked, invoices will be generated from sales invoices.If not, it will be generated from the sales order.'),
        ),
        migrations.CreateModel(
            name='TaxesAndCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erpnext_code', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_category', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='If checked, this tax and charges is going to be used.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.erpcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erpnext_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='If checked, this cost center is going to be used.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.erpcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
