# Generated by Django 4.2.15 on 2025-07-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0053_salesorderinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxesAndCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erpnext_code', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_category', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.erpcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
