# Generated by Django 4.2.15 on 2025-07-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0054_erppaymenttermtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
