# Generated by Django 4.2.15 on 2025-07-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0055_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='invoice_id',
            field=models.CharField(blank=True, help_text='Invoice id on the payment gateway.', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='is_main_invoice',
            field=models.BooleanField(default=True),
        ),
    ]
