# Generated by Django 4.2.15 on 2025-09-15 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geohosting', '0056_salesorder_invoice_id_salesorder_is_main_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaymentGatewayId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe', models.TextField(blank=True, null=True)),
                ('paystack', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
