# Generated by Django 4.2.15 on 2025-09-15 06:47

import django.core.validators
from django.db import migrations, models
import geohosting.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0057_userpaymentgatewayid'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='discount_amount',
            field=models.IntegerField(blank=True, help_text='Discount amount if not using percentage.', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_percentage',
            field=models.IntegerField(blank=True, help_text='Discount percentage.', null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='app_name',
            field=models.CharField(blank=True, help_text='App name that would be used for instance.It will also be used for sub domain.', null=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Name may only contain lowercase letters, numbers or dashes (not at start or end).'), geohosting.validators.app_name_validator]),
        ),
    ]
