# Generated by Django 4.2.15 on 2025-10-17 02:59

from django.db import migrations, models
import django.db.models.deletion
import geohosting.models.coupon


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0058_salesorder_discount_amount_salesorder_discount_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name may only contain letters, numbers, and hyphens (-). It cannot start or end with a hyphen, nor contain consecutive hyphens.', max_length=256, unique=True, validators=[geohosting.models.coupon.validate_coupon_name])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount_percentage', models.IntegerField(blank=True, help_text='Discount percentage', null=True)),
                ('discount_amount', models.IntegerField(blank=True, help_text='Discount amount, it will be ignored if discount percentage is set', null=True)),
                ('duration', models.IntegerField(help_text='Duration of coupon code group in months.')),
                ('stripe_id', models.CharField(blank=True, max_length=256, null=True)),
                ('paystack_id', models.CharField(blank=True, max_length=256, null=True)),
                ('currency', models.CharField(blank=True, choices=[('ZAR', 'ZAR'), ('EUR', 'EUR'), ('USD', 'USD')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('stripe_code', models.CharField(blank=True, max_length=256, null=True)),
                ('paystack_code', models.CharField(blank=True, max_length=256, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.coupon')),
            ],
        ),
    ]
