# Generated by Django 4.2.15 on 2025-10-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0059_coupon_couponcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcode',
            old_name='paystack_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='couponcode',
            name='stripe_code',
        ),
        migrations.AddField(
            model_name='couponcode',
            name='code_used_on_paystack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='paystack_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponcode',
            name='stripe_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='paystack_id',
            field=models.CharField(blank=True, help_text='Price id on the paystack.This is for the product on the storefront. We split using the product because we need to apply .', null=True),
        ),
    ]
