# Generated by Django 4.2.15 on 2025-10-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0060_rename_paystack_code_couponcode_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_on',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url_as_addon',
        ),
        migrations.AddField(
            model_name='product',
            name='is_username_credential_use_email',
            field=models.BooleanField(default=False, help_text='If this is true, the username credential will be the email.'),
        ),
        migrations.CreateModel(
            name='ProductAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, help_text='URL of the product as add-on, example: geoserver on the geonode is "/geoserver". Or if a static one, you could put : http://<instance_name>.addon.<cluster_domain>', max_length=256, null=True)),
                ('is_instance_check', models.BooleanField(default=False, help_text='If this is true, the addon will be checked for instance availability')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='geohosting.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.product')),
            ],
        ),
    ]
