# Generated by Django 5.2.13 on 2026-05-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0061_remove_product_add_on_remove_product_url_as_addon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
