# Generated by Django 5.2.13 on 2026-05-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0061_remove_product_add_on_remove_product_url_as_addon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderAutoRepeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erpnext_code', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half-yearly', 'Half-yearly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('repeat_on_day', models.IntegerField()),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('notify_by_email', models.BooleanField(default=True)),
                ('submit_on_creation', models.BooleanField(default=True)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geohosting.salesorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
